"""compare.py

Pixel-level comparison between the reference image and the current D3 reconstruction.

Outputs:
- reconstruction.png  (generated by render.py each run unless --no-render)
- diff.png            (auto-contrasted and contrast-boosted diff for inspection)

Metrics (printed):
- MAE  (mean absolute error) averaged over RGBA channels, in [0, 255]
- RMSE (root mean squared error) averaged over RGBA channels, in [0, 255]

Run:
  uv run python compare.py

Tip:
- If MAE/RMSE won't decrease, you likely have alignment / font / stroke-width mismatch.
- Flip-check warning is heuristic but computed (not guessed): it compares against flipped variants.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

from PIL import Image, ImageChops, ImageEnhance, ImageOps, ImageStat


def compute_metrics(diff: Image.Image) -> tuple[float, float]:
    """Return (MAE, RMSE) averaged over channels."""
    stat = ImageStat.Stat(diff)
    mae = sum(stat.mean) / len(stat.mean)
    rmse = sum(stat.rms) / len(stat.rms)
    return float(mae), float(rmse)


def _diff_metrics(ref: Image.Image, rec: Image.Image) -> tuple[float, float]:
    d = ImageChops.difference(ref, rec)
    return compute_metrics(d)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--reference", type=Path, default=Path("public/reference.png"))
    parser.add_argument("--reconstruction", type=Path, default=Path("reconstruction.png"))
    parser.add_argument("--diff", type=Path, default=Path("diff.png"))
    parser.add_argument("--no-render", action="store_true", help="Do not auto-run render.py")
    parser.add_argument(
        "--flip-check",
        action="store_true",
        default=True,
        help="Check whether flipped reconstructions match better (default: on).",
    )
    parser.add_argument(
        "--no-flip-check",
        action="store_false",
        dest="flip_check",
        help="Disable flip check.",
    )
    args = parser.parse_args()

    reference_path: Path = args.reference
    reconstruction_path: Path = args.reconstruction
    diff_path: Path = args.diff

    if not reference_path.exists():
        raise FileNotFoundError(f"Reference image not found: {reference_path}")

    # Always render into the requested reconstruction path (robust; avoids stale-path bugs)
    if not args.no_render:
        subprocess.check_call([sys.executable, "render.py", "--out", str(reconstruction_path)])

    if not reconstruction_path.exists():
        raise FileNotFoundError(
            f"Reconstruction screenshot not found: {reconstruction_path}. Run: uv run python render.py"
        )

    ref = Image.open(reference_path).convert("RGBA")
    rec = Image.open(reconstruction_path).convert("RGBA")

    ##if ref.size != rec.size:
    ##    raise ValueError(
    ##        f"Image size mismatch: reference={ref.size}, reconstruction={rec.size}. "
    ##        "Make sure the rendered canvas size matches reference.png size."
    ##    )
    if ref.size != rec.size:
        rw, rh = rec.size
        fw, fh = ref.size
        dw, dh = rw - fw, rh - fh

        # Allow off-by-one due to screenshot rounding (common in Playwright element screenshots).
        if abs(dw) <= 1 and abs(dh) <= 1:
            # If rec is larger, crop the extra pixels; if rec is smaller, still fail.
            if dw < 0 or dh < 0:
                raise ValueError(
                    f"Image size mismatch: reference={ref.size}, reconstruction={rec.size}. "
                    "Rendered image is smaller than reference; fix canvas sizing."
                )
            rec = rec.crop((0, 0, fw, fh))
        else:
            raise ValueError(
                f"Image size mismatch: reference={ref.size}, reconstruction={rec.size}. "
                "Make sure the rendered canvas size matches reference.png size."
            )

    diff = ImageChops.difference(ref, rec)
    mae, rmse = compute_metrics(diff)

    # Make diff easier to inspect
    diff_vis = ImageOps.autocontrast(diff.convert("RGB"))
    diff_vis = ImageEnhance.Contrast(diff_vis).enhance(6.0)
    diff_vis.save(diff_path)

    print(f"Reference:      {reference_path} ({ref.size[0]}x{ref.size[1]})")
    print(f"Reconstruction: {reconstruction_path}")
    print(f"Diff saved:     {diff_path}")
    print(f"MAE:  {mae:.4f} / 255")
    print(f"RMSE: {rmse:.4f} / 255")

    # Detect flip issues (computed comparison, not guess)
    if args.flip_check:
        # candidate flips
        candidates = {
            "vflip": ImageOps.flip(rec),                   # top-bottom
            "hflip": ImageOps.mirror(rec),                 # left-right
            "vhflip": ImageOps.mirror(ImageOps.flip(rec)), # both
        }

        best_name = None
        best_mae = mae
        best_rmse = rmse

        for name, rec_alt in candidates.items():
            m, r = _diff_metrics(ref, rec_alt)
            if (m < best_mae) or (m == best_mae and r < best_rmse):
                best_name, best_mae, best_rmse = name, m, r

        # Only warn if meaningfully better (avoid noise)
        # Can tune these thresholds; current values are conservative.
        if best_name is not None and (best_mae + 1.0 < mae) and (best_rmse + 1.0 < rmse):
            print(
                "WARNING: A flipped reconstruction matches the reference noticeably better. "
                "This usually means your axis/domain order or coordinate mapping is inverted.\n"
                f"         Best flip: {best_name}"
            )
            print(f"Flip-check ({best_name}) MAE:  {best_mae:.4f} / 255")
            print(f"Flip-check ({best_name}) RMSE: {best_rmse:.4f} / 255")


if __name__ == "__main__":
    main()
